/**
 * Application error codes.
 * Every error in the system maps to one of these codes.
 */
export const ErrorCode = {
  // ─── General ──────────────────────────────────────────────
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  BAD_REQUEST: "BAD_REQUEST",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // ─── Auth ─────────────────────────────────────────────────
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // ─── OTP ──────────────────────────────────────────────────
  OTP_SEND_FAILED: "OTP_SEND_FAILED",
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_RATE_LIMITED: "OTP_RATE_LIMITED",

  // ─── SMS ──────────────────────────────────────────────────
  SMS_SEND_FAILED: "SMS_SEND_FAILED",
  SMS_INSUFFICIENT_BALANCE: "SMS_INSUFFICIENT_BALANCE",
  SMS_INVALID_PHONE: "SMS_INVALID_PHONE",
  SMS_GATEWAY_INACTIVE: "SMS_GATEWAY_INACTIVE",

  // ─── Domain ───────────────────────────────────────────────
  STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
  MACHINE_NOT_FOUND: "MACHINE_NOT_FOUND",
  HALL_NOT_FOUND: "HALL_NOT_FOUND",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  CONTRACT_NOT_FOUND: "CONTRACT_NOT_FOUND",
  FAULT_NOT_FOUND: "FAULT_NOT_FOUND",

  MACHINE_NOT_AVAILABLE: "MACHINE_NOT_AVAILABLE",
  MACHINE_ALREADY_ASSIGNED: "MACHINE_ALREADY_ASSIGNED",
  SCHEDULE_CONFLICT: "SCHEDULE_CONFLICT",
  CONTRACT_EXPIRED: "CONTRACT_EXPIRED",
  PAYMENT_ALREADY_COMPLETED: "PAYMENT_ALREADY_COMPLETED",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

  // ─── File ─────────────────────────────────────────────────
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_TYPE_NOT_ALLOWED: "FILE_TYPE_NOT_ALLOWED",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * Maps error codes to default HTTP status codes.
 */
export const ErrorHttpStatus: Record<ErrorCodeType, number> = {
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.VALIDATION_ERROR]: 422,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.METHOD_NOT_ALLOWED]: 405,
  [ErrorCode.TOO_MANY_REQUESTS]: 429,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,

  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.SESSION_EXPIRED]: 401,
  [ErrorCode.ACCOUNT_DISABLED]: 403,
  [ErrorCode.EMAIL_NOT_VERIFIED]: 403,

  [ErrorCode.OTP_SEND_FAILED]: 500,
  [ErrorCode.OTP_INVALID]: 400,
  [ErrorCode.OTP_EXPIRED]: 400,
  [ErrorCode.OTP_RATE_LIMITED]: 429,

  [ErrorCode.SMS_SEND_FAILED]: 500,
  [ErrorCode.SMS_INSUFFICIENT_BALANCE]: 503,
  [ErrorCode.SMS_INVALID_PHONE]: 400,
  [ErrorCode.SMS_GATEWAY_INACTIVE]: 503,

  [ErrorCode.STUDENT_NOT_FOUND]: 404,
  [ErrorCode.MACHINE_NOT_FOUND]: 404,
  [ErrorCode.HALL_NOT_FOUND]: 404,
  [ErrorCode.ROOM_NOT_FOUND]: 404,
  [ErrorCode.PAYMENT_NOT_FOUND]: 404,
  [ErrorCode.CONTRACT_NOT_FOUND]: 404,
  [ErrorCode.FAULT_NOT_FOUND]: 404,

  [ErrorCode.MACHINE_NOT_AVAILABLE]: 409,
  [ErrorCode.MACHINE_ALREADY_ASSIGNED]: 409,
  [ErrorCode.SCHEDULE_CONFLICT]: 409,
  [ErrorCode.CONTRACT_EXPIRED]: 400,
  [ErrorCode.PAYMENT_ALREADY_COMPLETED]: 409,
  [ErrorCode.DUPLICATE_ENTRY]: 409,

  [ErrorCode.FILE_TOO_LARGE]: 413,
  [ErrorCode.FILE_TYPE_NOT_ALLOWED]: 415,
  [ErrorCode.FILE_UPLOAD_FAILED]: 500,
};
